name: tuk_meal
description: "A food ordering and meal management app for TUK students and staff."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.2
  flutter_blurhash: ^0.9.1
  intl: ^0.20.2
  flutter_dotenv: ^6.0.0
  http: ^1.5.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/splash/
    - .env

flutter_icons:
  android: true
  ios: true
  image_path: assets/icons/icon.png

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#FFFFFF"
  image: assets/splash/splashicon.png
  image_dark: assets/splash/splashicon.png
  android: true
  ios: true
  fullscreen: true
  android_gravity: center
  ios_content_mode: center
  android_12:
    image: assets/splash/splashicon.png
    icon_background_color: "#FFFFFF"
    image_dark: assets/splash/splashicon.png
    icon_background_color_dark: "#FFFFFF"
